In [34]:
import numpy as np

arr = np.array((1, 2, 3))
arr

array([1, 2, 3])

In [35]:
arr = np.zeros((2, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
arr = np.ones((2, 3, 4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
arr = np.arange(5, 25, 5)
arr

array([ 5, 10, 15, 20])

In [52]:
arr.shape

(4,)

In [53]:
arr.dtype

dtype('int64')

In [58]:
arr[-1]

np.int64(20)

In [59]:
arr[1:3]

array([10, 15])

In [62]:
arr[0] + arr[3]

np.int64(25)

In [63]:
arr[1] * arr[-1]

np.int64(200)

In [64]:
arr.mean()

np.float64(12.5)